# version: "3.8"

# services:
#   backend:
#     build: .
#     container_name: express-app
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - REDIS_URL=redis://redis:6379
#     depends_on:
#       - redis
#     networks:
#       - backend-net

#   redis:
#     image: redis:7-alpine
#     container_name: redis-server
#     ports:
#       - "6379:6379"
#     networks:
#       - backend-net

# networks:
#   backend-net:
#     driver: bridge



version: "3.8"

services:
  backend:
    build: .
    container_name: express-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
